#!/usr/bin/env python3
"""
Bulk Tariff Management - Effect Generator
==========================================
Reads Victoria 3's goods definition file and regenerates
common/scripted_effects/00_bulk_tariff_effects.txt automatically.

Usage:
    python generate_effects.py

Optionally override the game path:
    python generate_effects.py "D:/SteamLibrary/steamapps/common/Victoria 3"

Re-run this whenever:
  - Victoria 3 updates and adds new goods
  - You add a mod that defines new goods in common/goods/
"""

import re
import sys
import os
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_GAME_PATH = r"D:\SteamLibrary\steamapps\common\Victoria 3"

GOODS_FILE_RELATIVE = r"game\common\goods\00_goods.txt"

OUTPUT_FILE = Path(__file__).parent / "common" / "scripted_effects" / "00_bulk_tariff_effects.txt"

TARIFF_LEVELS = [
    ("max",     "max_tariffs"),
    ("high",    "high_tariffs"),
    ("low",     "low_tariffs"),
    ("none",    "no_tariffs_or_subventions"),
    ("sub_low",  "low_subventions"),
    ("sub_high", "high_subventions"),
    ("sub_max",  "max_subventions"),
]

# ---------------------------------------------------------------------------
# Parse goods
# ---------------------------------------------------------------------------

def parse_tradeable_goods(goods_path: Path) -> list[str]:
    """
    Returns a list of good keys that are tradeable (i.e. can have tariffs set).
    Excludes goods marked with 'local = yes' or 'tradeable = no'.
    """
    text = goods_path.read_text(encoding="utf-8")

    # Strip comments
    text = re.sub(r"#[^\n]*", "", text)

    # Find each top-level block: key = { ... }
    # We use a simple brace-matching parser so nested braces work correctly.
    tradeable = []
    i = 0
    while i < len(text):
        # Find the next word (potential good key)
        m = re.search(r"\b([a-z_]+)\b\s*=\s*\{", text[i:])
        if not m:
            break

        key = m.group(1)
        start = i + m.end()  # position just after the opening {

        # Match braces to find the end of this block
        depth = 1
        j = start
        while j < len(text) and depth > 0:
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
            j += 1

        block = text[start:j - 1]
        i = j

        # Skip the outer GOODS = { ... } wrapper
        if key == "GOODS":
            continue

        # Skip if explicitly non-tradeable
        if re.search(r"\btradeable\s*=\s*no\b", block):
            continue

        # Skip if local (services, transportation, electricity)
        if re.search(r"\blocal\s*=\s*yes\b", block):
            continue

        tradeable.append(key)

    return tradeable


# ---------------------------------------------------------------------------
# Generate effects file
# ---------------------------------------------------------------------------

HEADER = """\
# Bulk Tariff Management - Scripted Effects
# AUTO-GENERATED by generate_effects.py — do not edit by hand.
# Re-run generate_effects.py to update for new goods.
#
# Goods included: {count} tradeable goods parsed from:
#   {source}
"""

def generate_effect_block(name: str, effect: str, goods: list[str], level: str) -> str:
    lines = [f"{name} = {{"]
    for good in goods:
        lines.append(f"\t{effect} = {{ goods = g:{good} level = {level} }}")
    lines.append("}\n")
    return "\n".join(lines)


def generate_file(goods: list[str], source_path: Path) -> str:
    sections = [HEADER.format(count=len(goods), source=source_path)]

    sections.append("### =========================================================")
    sections.append("### IMPORT TARIFFS")
    sections.append("### =========================================================\n")
    for suffix, level in TARIFF_LEVELS:
        block = generate_effect_block(
            f"bulk_tariff_import_{suffix}",
            "set_import_tariff_level",
            goods,
            level
        )
        sections.append(block)

    sections.append("### =========================================================")
    sections.append("### EXPORT TARIFFS")
    sections.append("### =========================================================\n")
    for suffix, level in TARIFF_LEVELS:
        block = generate_effect_block(
            f"bulk_tariff_export_{suffix}",
            "set_export_tariff_level",
            goods,
            level
        )
        sections.append(block)

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    game_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(DEFAULT_GAME_PATH)
    goods_path = game_path / GOODS_FILE_RELATIVE

    if not goods_path.exists():
        print(f"ERROR: Could not find goods file at:\n  {goods_path}")
        print("Pass your Victoria 3 install path as the first argument.")
        sys.exit(1)

    print(f"Reading goods from: {goods_path}")
    goods = parse_tradeable_goods(goods_path)
    print(f"Found {len(goods)} tradeable goods:")
    for g in goods:
        print(f"  {g}")

    content = generate_file(goods, goods_path)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"\nWrote {OUTPUT_FILE}")
    print("Done. Re-run this script whenever goods change.")


if __name__ == "__main__":
    main()
